=== huangzy0208/MyUtil/src/main/resources/xsd/MSAShipFilingDeclaration-0.1.XSD
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by wn (wn) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:Declaration:datamodel:standard:CN:MSAShipFilingDeclaration-0.1" targetNamespace="urn:Declaration:datamodel:standard:CN:MSAShipFilingDeclaration-0.1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="Type/ConveyanceDataType.xsd"/>
	<xs:include schemaLocation="Type/DeclarationTypeCode.xsd"/>
	<xs:include schemaLocation="Type/MessageDefine.xsd"/>
	<xs:include schemaLocation="Type/MessageHead.xsd"/>
	<xs:element name="Message">
		<xs:annotation>
			<xs:documentation>报文</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MessageHead" type="Head"/>
				<xs:element name="MessageBody">
					<xs:annotation>
						<xs:documentation>报文体</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Declaration">
								<xs:annotation>
									<xs:documentation>海事船舶备案申报(MSAShipFilingDeclaration-0.1)</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Archive" type="Information"/>
									</xs:sequence>
									<xs:attribute name="Xmlns" type="Xmlns" use="required" fixed="urn:Declaration:datamodel:standard:CN:MSAShipFilingDeclaration-0.1">
										<xs:annotation>
											<xs:documentation>报文体命名空间</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="DataModelVersion" type="DataModelVersion" use="required" fixed="0.1">
										<xs:annotation>
											<xs:documentation>报文体数据元模型版本号</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="Version" type="Version" use="required" fixed="0.1">
										<xs:annotation>
											<xs:documentation>报文体版本号</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Information">
		<xs:sequence>
			<xs:element name="ApplyId">
				<xs:annotation>
					<xs:documentation>备案编号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X16">
						<xs:length value="16"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="IMO">
				<xs:annotation>
					<xs:documentation>IMO编号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X20">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselNameEn">
				<xs:annotation>
					<xs:documentation>英文船名</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X50">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselNameCn">
				<xs:annotation>
					<xs:documentation>中文船名</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X50"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CallSign">
				<xs:annotation>
					<xs:documentation>船舶呼号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X9">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GrossTonnage">
				<xs:annotation>
					<xs:documentation>总吨位</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_10.3"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="NetTonnage">
				<xs:annotation>
					<xs:documentation>净吨位</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_10.3"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselType">
				<xs:annotation>
					<xs:documentation>船舶类型</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X20">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DeepDraft">
				<xs:annotation>
					<xs:documentation>满吃水</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DeadWeightTonnage">
				<xs:annotation>
					<xs:documentation>载重吨位</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_10.3"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MaxCrewSpeed">
				<xs:annotation>
					<xs:documentation>最大船速</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.3"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FlagCode">
				<xs:annotation>
					<xs:documentation>内贸船舶唯一识别码</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X30"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MMSI">
				<xs:annotation>
					<xs:documentation>船舶通讯号码MMSI</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X50"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="BuildFactory">
				<xs:annotation>
					<xs:documentation>船舶制造厂</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X20"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselLength">
				<xs:annotation>
					<xs:documentation>船长</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselBreadth">
				<xs:annotation>
					<xs:documentation>船宽</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselDeapth">
				<xs:annotation>
					<xs:documentation>船高</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="HorsePower">
				<xs:annotation>
					<xs:documentation>马力</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X15"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="HostNum" type="N8">
				<xs:annotation>
					<xs:documentation>主机数目</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="HostPower" type="Decimal_10.3">
				<xs:annotation>
					<xs:documentation>主机功率</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="VesselHost">
				<xs:annotation>
					<xs:documentation>船舶所有人</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X50"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CountryCode">
				<xs:annotation>
					<xs:documentation>国籍代码</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X6"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="HomeportCode">
				<xs:annotation>
					<xs:documentation>船籍港代码</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X6">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ShipRegistrationNumber">
				<xs:annotation>
					<xs:documentation>船舶登记号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X14"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FirstRegistrationNum">
				<xs:annotation>
					<xs:documentation>初次登记号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X14"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ShipInspectionRegistrationNum">
				<xs:annotation>
					<xs:documentation>船检登记号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X12"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="BrandBookNo">
				<xs:annotation>
					<xs:documentation>牌簿号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X20"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ShipRiverBoatFlag">
				<xs:annotation>
					<xs:documentation>海船内河船标志</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="S1"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Route">
				<xs:annotation>
					<xs:documentation>航线</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CompletionDate">
				<xs:annotation>
					<xs:documentation>建成日期</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="yyyyMMdd"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PropellerNumber">
				<xs:annotation>
					<xs:documentation>推进器个数</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="N4"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ApprovedWindRating">
				<xs:annotation>
					<xs:documentation>核定抗风等级</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MinimumFreeboard">
				<xs:annotation>
					<xs:documentation>最小干舷数字</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.3"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Slotting">
				<xs:annotation>
					<xs:documentation>箱位</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="N4"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ParkingSpacesNum">
				<xs:annotation>
					<xs:documentation>车位</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="N4"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GuestsNum">
				<xs:annotation>
					<xs:documentation>客位</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="N4"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Speed">
				<xs:annotation>
					<xs:documentation>航速</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_5.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ShipOperators">
				<xs:annotation>
					<xs:documentation>船舶经营人</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X60"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ProvincialMaritimeOrganisation">
				<xs:annotation>
					<xs:documentation>所属省级海事机构</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X6"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SocietyCode">
				<xs:annotation>
					<xs:documentation>船级社代码</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X6"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MinimumSafeManningNum">
				<xs:annotation>
					<xs:documentation>最低安全配员人数</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="N3"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="LifeSavingEquipmentMaxNum">
				<xs:annotation>
					<xs:documentation>救生设备最大人数</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="N5"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ICCard">
				<xs:annotation>
					<xs:documentation>IC卡号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X12"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="BarCode">
				<xs:annotation>
					<xs:documentation>条形码</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X12"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FlagShipNo">
				<xs:annotation>
					<xs:documentation>船舶标志号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X16"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="IssuerFlag">
				<xs:annotation>
					<xs:documentation>发卡标志</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="S1"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="RegistrationMark">
				<xs:annotation>
					<xs:documentation>登记标志</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="S1"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ShipClassification">
				<xs:annotation>
					<xs:documentation>船舶分类	</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="S1"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="RecodeDepart">
				<xs:annotation>
					<xs:documentation>录入单位</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X50"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Opertaion">
				<xs:annotation>
					<xs:documentation>录入人</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X50"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Memo">
				<xs:annotation>
					<xs:documentation>备注</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X255"/>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== huangzy0208/MyUtil/target/classes/template/MSAShipFilingDeclaration.xml
<#setting number_format="#">
<?xml version="1.0" encoding="UTF-8"?>
<Message xsi:schemaLocation="urn:Declaration:datamodel:standard:CN:MSAShipFilingDeclaration-0.1 MSAShipFilingDeclaration-0.1.XSD" xmlns="urn:Declaration:datamodel:standard:CN:MSAShipFilingDeclaration-0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<MessageHead>
		<MessageID>${messageHead.messageID!''}</MessageID>
		<MessageType>MSA0001</MessageType>
		<MessageMark>0</MessageMark>
		<SenderID>${messageHead.senderID!''}</SenderID>
		<ReceiverID>${messageHead.receiverID!''}</ReceiverID>
		<ActualSenderID>${messageHead.actualSenderID!''}</ActualSenderID>
		<ActualReceiverID>${messageHead.actualReceiverID!''}</ActualReceiverID>
		<SendTime>${messageHead.sendTime!''}</SendTime>
		<Version>${messageHead.version!''}</Version>
		<SendNum>1</SendNum>
	</MessageHead>
	<MessageBody>
		<Declaration DataModelVersion="0.1" Xmlns="urn:Declaration:datamodel:standard:CN:MSAShipFilingDeclaration-0.1" Version="0.1">
			<Archive>
				<ApplyId><![CDATA[${messageBody.bodyElement.applyId!''}]]></ApplyId>
				<IMO><![CDATA[${messageBody.bodyElement.imo!''}]]></IMO>
				<VesselNameEn><![CDATA[${messageBody.bodyElement.nameEn!''}]]></VesselNameEn>
				<VesselNameCn><![CDATA[${messageBody.bodyElement.nameCn!''}]]></VesselNameCn>
				<CallSign><![CDATA[${messageBody.bodyElement.callName!''}]]></CallSign>
				<GrossTonnage><![CDATA[${messageBody.bodyElement.totalTon!''}]]></GrossTonnage>
				<NetTonnage><![CDATA[${messageBody.bodyElement.netTon!''}]]></NetTonnage>
				<VesselType><![CDATA[${messageBody.bodyElement.shipType!''}]]></VesselType>
				<DeepDraft><![CDATA[${messageBody.bodyElement.draftDepth!''}]]></DeepDraft>
				<DeadWeightTonnage><![CDATA[${messageBody.bodyElement.capacityTon!''}]]></DeadWeightTonnage>
				<MaxCrewSpeed><![CDATA[${messageBody.bodyElement.maxSpeed!''}]]></MaxCrewSpeed>
				<FlagCode><![CDATA[${messageBody.bodyElement.innerCommerceId!''}]]></FlagCode>
				<MMSI><![CDATA[${messageBody.bodyElement.mmsi!''}]]></MMSI>
				<BuildFactory><![CDATA[${messageBody.bodyElement.manufacturer!''}]]></BuildFactory>
				<VesselLength><![CDATA[${messageBody.bodyElement.totalLength!''}]]></VesselLength>
				<VesselBreadth><![CDATA[${messageBody.bodyElement.width!''}]]></VesselBreadth>
				<VesselDeapth><![CDATA[${messageBody.bodyElement.height!''}]]></VesselDeapth>
				<HorsePower><![CDATA[${messageBody.bodyElement.shipHorsepower!''}]]></HorsePower>
				<HostNum><![CDATA[${messageBody.bodyElement.engineCount!''}]]></HostNum>
				<HostPower><![CDATA[${messageBody.bodyElement.enginePower!''}]]></HostPower>
				<VesselHost><![CDATA[${messageBody.bodyElement.ownerCn!''}]]></VesselHost>
				<CountryCode><![CDATA[${messageBody.bodyElement.nationalityEn!''}]]></CountryCode>
				<HomeportCode><![CDATA[${messageBody.bodyElement.nationalityPort!''}]]></HomeportCode>
				<ShipRegistrationNumber>船舶登记号</ShipRegistrationNumber>
				<FirstRegistrationNum>初次登记号</FirstRegistrationNum>
				<ShipInspectionRegistrationNum>船检登记号</ShipInspectionRegistrationNum>
				<BrandBookNo>牌簿号</BrandBookNo>
				<ShipRiverBoatFlag>海船内河船标志</ShipRiverBoatFlag>
				<Route>航线</Route>
				<CompletionDate><![CDATA[${messageBody.bodyElement.dateBuild!''}]]></CompletionDate>
				<PropellerNumber><![CDATA[${messageBody.bodyElement.engineCount!''}]]></PropellerNumber>
				<ApprovedWindRating>核定抗风等级</ApprovedWindRating>
				<MinimumFreeboard>最小干舷数字</MinimumFreeboard>
				<Slotting>箱位</Slotting>
				<ParkingSpacesNum>车位</ParkingSpacesNum>
				<GuestsNum>客位</GuestsNum>
				<Speed>航速</Speed>
				<ShipOperators>船舶经营人</ShipOperators>
				<ProvincialMaritimeOrganisation>所属省级海事机构</ProvincialMaritimeOrganisation>
				<SocietyCode>船级社代码</SocietyCode>
				<MinimumSafeManningNum>最低安全配员人数</MinimumSafeManningNum>
				<LifeSavingEquipmentMaxNum>救生设备最大人数</LifeSavingEquipmentMaxNum>
				<ICCard>IC卡号</ICCard>
				<BarCode>条形码</BarCode>
				<FlagShipNo>船舶标志号</FlagShipNo>
				<IssuerFlag>发卡标志</IssuerFlag>
				<RegistrationMark>登记标志</RegistrationMark>
				<ShipClassification><![CDATA[${messageBody.bodyElement.shipType!''}]]></ShipClassification>
				<RecodeDepart><![CDATA[${messageBody.bodyElement.recordDepartment!''}]]></RecodeDepart>
				<Opertaion><![CDATA[${messageBody.bodyElement.recorder!''}]]></Opertaion>
				<Memo><![CDATA[${messageBody.bodyElement.remark!''}]]></Memo>
			</Archive>
		</Declaration>
	</MessageBody>
</Message>
