=== huangzy0208/MyUtil/src/main/resources/xsd/Type/MSAShipPreArrivalDeclaration-0.1.XSD
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by tt (tt) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:Declaration:datamodel:standard:CN:MSAShipPreArrivalDeclaration-0.1" targetNamespace="urn:Declaration:datamodel:standard:CN:MSAShipPreArrivalDeclaration-0.1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="ConveyanceDataType.xsd"/>
	<xs:include schemaLocation="DeclarationTypeCode.xsd"/>
	<xs:include schemaLocation="MessageDefine.xsd"/>
	<xs:include schemaLocation="MessageHead.xsd"/>
	<xs:element name="Message">
		<xs:annotation>
			<xs:documentation>报文</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MessageHead" type="Head"/>
				<xs:element name="MessageBody">
					<xs:annotation>
						<xs:documentation>报文体</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Declaration">
								<xs:annotation>
									<xs:documentation>海事船舶进口岸预报(MSAShipPreArrivalDeclaration-0.1)</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Apply" type="Apply"/>
										<xs:element name="AttachmentLists" type="AttachmentLists"/>
									</xs:sequence>
									<xs:attribute name="Xmlns" type="Xmlns" use="required" fixed="urn:Declaration:datamodel:standard:CN:MSAShipPreArrivalDeclaration-0.1">
										<xs:annotation>
											<xs:documentation>报文体命名空间</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="DataModelVersion" type="DataModelVersion" use="required" fixed="0.1">
										<xs:annotation>
											<xs:documentation>报文体数据元模型版本号</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="Version" type="Version" use="required" fixed="0.1">
										<xs:annotation>
											<xs:documentation>报文体版本号</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Apply">
		<xs:sequence>
			<xs:element name="ApplyId">
				<xs:annotation>
					<xs:documentation>预报申报号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X14">
						<xs:length value="14"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ShipNo">
				<xs:annotation>
					<xs:documentation>船舶编号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X20">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="IMO">
				<xs:annotation>
					<xs:documentation>IMO编号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X10">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="NameEn">
				<xs:annotation>
					<xs:documentation>英文船名</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X40">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="NameCn">
				<xs:annotation>
					<xs:documentation>中文船名</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X20">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="NationalCn">
				<xs:annotation>
					<xs:documentation>中文国籍</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X10">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SecLevelGrade">
				<xs:annotation>
					<xs:documentation>保安等级</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X1">
						<xs:length value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselHostCN">
				<xs:annotation>
					<xs:documentation>船舶所有人中文</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X80"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselHostEN">
				<xs:annotation>
					<xs:documentation>船舶所有人英文</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X80"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CallNum">
				<xs:annotation>
					<xs:documentation>呼号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X10">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselLength" type="X9">
				<xs:annotation>
					<xs:documentation>船舶长度</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="VesselWide" type="X9">
				<xs:annotation>
					<xs:documentation>船舶宽度</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="VesselAllTone" type="X8">
				<xs:annotation>
					<xs:documentation>总吨位</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="VesselNetTone" type="X8">
				<xs:annotation>
					<xs:documentation>净吨位</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="LoadingTone" type="X8">
				<xs:annotation>
					<xs:documentation>载重吨</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="SeqvVoyage">
				<xs:annotation>
					<xs:documentation>进口航次</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X12">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="StartPort">
				<xs:annotation>
					<xs:documentation>出发港</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X30">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="StartDate" type="yyyyMMdd">
				<xs:annotation>
					<xs:documentation>出发日期</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="PassPort">
				<xs:annotation>
					<xs:documentation>经过港口</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X30"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ArrivalDate" type="yyyyMMdd">
				<xs:annotation>
					<xs:documentation>抵港时间</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="BerthCode">
				<xs:annotation>
					<xs:documentation>预靠泊位</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X4">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselType">
				<xs:annotation>
					<xs:documentation>船舶类型</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X4">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ProDraw">
				<xs:annotation>
					<xs:documentation>进口吃水(前吃水)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="EndDraw">
				<xs:annotation>
					<xs:documentation>进口吃水(后吃水)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VesselSpeed" type="X6">
				<xs:annotation>
					<xs:documentation>船速</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="AwayDate" type="yyyyMMdd">
				<xs:annotation>
					<xs:documentation>离港时间</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="BoundPort">
				<xs:annotation>
					<xs:documentation>开往港口</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X30">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DeportMaxDraw">
				<xs:annotation>
					<xs:documentation>出口最大吃水</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="InpTravellerTotal" type="N8">
				<xs:annotation>
					<xs:documentation>进口旅客总数</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="InpMaleChinaCrew" type="N8">
				<xs:annotation>
					<xs:documentation>进口中籍船员男</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="InpFemaleChinaCrew" type="N8">
				<xs:annotation>
					<xs:documentation>进口中籍船员女</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="InpMaleForeignCrew" type="N8">
				<xs:annotation>
					<xs:documentation>进口外籍船员男</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="InpFemaleForeignCrew">
				<xs:annotation>
					<xs:documentation>进口外籍船员女</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="IMMeterialName">
				<xs:annotation>
					<xs:documentation>进口载货名称</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X150"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ExMeterialName">
				<xs:annotation>
					<xs:documentation>出口载货名称</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X150"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="InpMeterialNum">
				<xs:annotation>
					<xs:documentation>载货总吨数</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="InpNormalMaterialNum">
				<xs:annotation>
					<xs:documentation>进口普通货物吨数</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="InpHazardouMaterialNum">
				<xs:annotation>
					<xs:documentation>进口危险货物吨数</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ExpTravellerNum" type="N8">
				<xs:annotation>
					<xs:documentation>出口旅客总数</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ExpCnMaleCrew" type="N8">
				<xs:annotation>
					<xs:documentation>出口中籍船员男</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ExpCnFemaleCrew" type="N8">
				<xs:annotation>
					<xs:documentation>出口中籍船员女</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ExpMaleForeignCrew" type="N8">
				<xs:annotation>
					<xs:documentation>出口外籍船员男</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ExpFemaleForeignCrew" type="N8">
				<xs:annotation>
					<xs:documentation>出口外籍船员女</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ExportMeterialNum">
				<xs:annotation>
					<xs:documentation>出口载货吨数</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ExportNormalMaterialNum">
				<xs:annotation>
					<xs:documentation>出口普通货物吨数</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ExportHazardouMaterialNum">
				<xs:annotation>
					<xs:documentation>出口危险货物吨数</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="Decimal_8.2"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ApplyCompany">
				<xs:annotation>
					<xs:documentation>申报单位</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X100"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ApplyName">
				<xs:annotation>
					<xs:documentation>申报员</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X20"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ReviceDepart">
				<xs:annotation>
					<xs:documentation>报给单位</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X6">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Flag">
				<xs:annotation>
					<xs:documentation>国际国内</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X1"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Memo">
				<xs:annotation>
					<xs:documentation>备注</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X250"/>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AttachmentLists">
		<xs:sequence>
			<xs:element name="AttachmentInfo" type="AttachmentInfo" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AttachmentInfo">
		<xs:sequence>
			<xs:element name="AttachmentNo">
				<xs:annotation>
					<xs:documentation>序号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="N6">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="AttachmentId">
				<xs:annotation>
					<xs:documentation>附件ID(文件创建名称)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X200">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="AttachmentName">
				<xs:annotation>
					<xs:documentation>文件名称</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="X255">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Remark" type="X200">
				<xs:annotation>
					<xs:documentation>备注</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== huangzy0208/MyUtil/target/classes/template/MSAShipPreArrivalDeclaration.xml
<#setting number_format="#">
<#include "public.ftl">
<?xml version="1.0" encoding="UTF-8"?>
<Message xsi:schemaLocation="urn:Declaration:datamodel:standard:CN:MSAShipPreArrivalDeclaration-0.1 MSAShipPreArrivalDeclaration-0.1.XSD" xmlns="urn:Declaration:datamodel:standard:CN:MSAShipPreArrivalDeclaration-0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<MessageHead>
		<MessageID>${messageHead.messageID!''}</MessageID>
		<MessageType>MSA0003</MessageType>
		<MessageMark>0</MessageMark>
		<SenderID>${messageHead.senderID!''}</SenderID>
		<ReceiverID>${messageHead.receiverID!''}</ReceiverID>
		<ActualSenderID>${messageHead.actualSenderID!''}</ActualSenderID>
		<ActualReceiverID>${messageHead.actualReceiverID!''}</ActualReceiverID>
		<SendTime>${messageHead.sendTime!''}</SendTime>
		<Version>${messageHead.version!''}</Version>
		<SendNum>1</SendNum>
	</MessageHead>
	<MessageBody>
		<Declaration Xmlns="urn:Declaration:datamodel:standard:CN:MSAShipPreArrivalDeclaration-0.1" DataModelVersion="0.1" Version="0.1">
			<Apply>
				<ApplyId><![CDATA[${messageBody.bodyElement.decId!''}]]></ApplyId>
				<ShipNo><![CDATA[${messageBody.bodyElement.basicInfo.shipNo!''}]]></ShipNo>
				<IMO><![CDATA[${messageBody.bodyElement.basicInfo.imo!''}]]></IMO>
				<NameEn><![CDATA[${messageBody.bodyElement.basicInfo.nameEn!''}]]></NameEn>
				<NameCn><![CDATA[${messageBody.bodyElement.basicInfo.nameCn!''}]]></NameCn>
				<NationalCn><![CDATA[${messageBody.bodyElement.basicInfo.nationalityCn!''}]]></NationalCn>
				<SecLevelGrade><![CDATA[${messageBody.bodyElement.basicInfo.securityRank!''}]]></SecLevelGrade>
				<VesselHostCN><![CDATA[${messageBody.bodyElement.basicInfo.ownerCn!''}]]></VesselHostCN>
				<VesselHostEN><![CDATA[${messageBody.bodyElement.basicInfo.ownerEn!''}]]></VesselHostEN>
				<CallNum><![CDATA[${messageBody.bodyElement.basicInfo.callName!''}]]></CallNum>
				<VesselLength><![CDATA[${messageBody.bodyElement.basicInfo.totalLength!''}]]></VesselLength>
				<VesselWide><![CDATA[${messageBody.bodyElement.basicInfo.totalLength!''}]]></VesselWide>
				<VesselAllTone><![CDATA[${messageBody.bodyElement.basicInfo.totalTon!''}]]></VesselAllTone>
				<VesselNetTone><![CDATA[${messageBody.bodyElement.basicInfo.netTon!''}]]></VesselNetTone>
				<LoadingTone><![CDATA[${messageBody.bodyElement.basicInfo.capacityTon!''}]]></LoadingTone>
				<SeqvVoyage><![CDATA[${messageBody.bodyElement.addInfo.sailings!''}]]></SeqvVoyage>
				<StartPort><![CDATA[${messageBody.bodyElement.addInfo.departurePort!''}]]></StartPort>
				<StartDate>${translateDate(messageBody.bodyElement.addInfo.dateDeparture!'','yyyy-MM-dd','yyyyMMdd')!''}</StartDate>
				<PassPort><![CDATA[${messageBody.bodyElement.addInfo.passPort!''}]]></PassPort>
				<ArrivalDate>${translateDate(messageBody.bodyElement.addInfo.dateArrival!'','yyyy-MM-dd','yyyyMMdd')!''}</ArrivalDate>
				<BerthCode><![CDATA[${messageBody.bodyElement.addInfo.berthCode!''}]]></BerthCode>
				<VesselType><![CDATA[${messageBody.bodyElement.addInfo.shipType!''}]]></VesselType>
				<ProDraw><![CDATA[${messageBody.bodyElement.addInfo.frontDraft!''}]]></ProDraw>
				<EndDraw><![CDATA[${messageBody.bodyElement.addInfo.backDraft!''}]]></EndDraw>
				<VesselSpeed><![CDATA[${messageBody.bodyElement.addInfo.speed!''}]]></VesselSpeed>
				<AwayDate>${translateDate(messageBody.bodyElement.addInfo.dateLeave!'','yyyy-MM-dd','yyyyMMdd')!''}</AwayDate>
				<BoundPort><![CDATA[${messageBody.bodyElement.addInfo.destPort!''}]]></BoundPort>
				<DeportMaxDraw><![CDATA[${messageBody.bodyElement.addInfo.expMaxDraft!''}]]></DeportMaxDraw>
				<InpTravellerTotal><![CDATA[${messageBody.bodyElement.cargoInfo.impPsngCnt!''}]]></InpTravellerTotal>
				<InpMaleChinaCrew><![CDATA[${messageBody.bodyElement.cargoInfo.impCnCrewMale!''}]]></InpMaleChinaCrew>
				<InpFemaleChinaCrew><![CDATA[${messageBody.bodyElement.cargoInfo.impCnCrewFemale!''}]]></InpFemaleChinaCrew>
				<InpMaleForeignCrew><![CDATA[${messageBody.bodyElement.cargoInfo.impForeignCrewMale!''}]]></InpMaleForeignCrew>
				<InpFemaleForeignCrew><![CDATA[${messageBody.bodyElement.cargoInfo.impForeignCrewFemale!''}]]></InpFemaleForeignCrew>
				<IMMeterialName><![CDATA[${messageBody.bodyElement.cargoInfo.impGoodsName!''}]]></IMMeterialName>
				<ExMeterialName><![CDATA[${messageBody.bodyElement.cargoInfo.expCargoName!''}]]></ExMeterialName>
				<InpMeterialNum><![CDATA[${messageBody.bodyElement.cargoInfo.impCargoTon!''}]]></InpMeterialNum>
				<InpNormalMaterialNum><![CDATA[${messageBody.bodyElement.cargoInfo.impGeneralGoodsTon!''}]]></InpNormalMaterialNum>
				<InpHazardouMaterialNum><![CDATA[${messageBody.bodyElement.cargoInfo.impDangerousCargoTon!''}]]></InpHazardouMaterialNum>
				<ExpTravellerNum><![CDATA[${messageBody.bodyElement.cargoInfo.expPsngs!''}]]></ExpTravellerNum>
				<ExpCnMaleCrew><![CDATA[${messageBody.bodyElement.cargoInfo.expCnCrewMale!''}]]></ExpCnMaleCrew>
				<ExpCnFemaleCrew><![CDATA[${messageBody.bodyElement.cargoInfo.expCnCrewFemale!''}]]></ExpCnFemaleCrew>
				<ExpMaleForeignCrew><![CDATA[${messageBody.bodyElement.cargoInfo.expForeignCrewMale!''}]]></ExpMaleForeignCrew>
				<ExpFemaleForeignCrew><![CDATA[${messageBody.bodyElement.cargoInfo.expForeignCrewFemale!''}]]></ExpFemaleForeignCrew>
				<ExportMeterialNum><![CDATA[${messageBody.bodyElement.cargoInfo.expCargoTon!''}]]></ExportMeterialNum>
		    <ExportNormalMaterialNum><![CDATA[${messageBody.bodyElement.cargoInfo.expGeneralCargoTon!''}]]></ExportNormalMaterialNum>
        <ExportHazardouMaterialNum><![CDATA[${messageBody.bodyElement.cargoInfo.expDangerousGoodsTon!''}]]></ExportHazardouMaterialNum>
				<ApplyCompany><![CDATA[${messageBody.bodyElement.other.decCompany!''}]]></ApplyCompany>
				<ApplyName><![CDATA[${messageBody.bodyElement.other.decPerson!''}]]></ApplyName>
				<ReviceDepart><![CDATA[${messageBody.bodyElement.other.reportToDepartment!''}]]></ReviceDepart>
				<Flag><![CDATA[${messageBody.bodyElement.other.ifInternational!''}]]></Flag>
				<Memo><![CDATA[${messageBody.bodyElement.other.remarks!''}]]></Memo>
			</Apply>
			<AttachmentLists>
				<#if ((messageBody.bodyElement.attachmentInfo??)&(messageBody.bodyElement.attachmentInfo?size gt 0))>
				<#list messageBody.bodyElement.attachmentInfo as item>
				<AttachmentInfo>
					<AttachmentNo>${item_index+1}</AttachmentNo>
					<AttachmentId><![CDATA[${item.trueFileName!''}]]></AttachmentId>
					<AttachmentName><![CDATA[${item.fileName!''}]]></AttachmentName>
					<Remark><![CDATA[${item.remark!''}]]></Remark>
				</AttachmentInfo>
				</#list>
				</#if>
			</AttachmentLists>		</Declaration>
	</MessageBody>
</Message>
